service: marvel-characters-back

provider:
  name: google
  runtime: nodejs8
  project: 'premium-modem-210713'
  credentials: ~/.gcloud/keyfile.json


plugins:
  - serverless-google-cloudfunctions

package:
  exclude:
    - node_modules/**
    - .gitignore
    - .git/**

functions:
  characters:
    handler: app
    events:
      - http: api/characters
